// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ProjetoDietas.Models;

#nullable disable

namespace ProjetoDietas.Migrations
{
    [DbContext(typeof(AppDataContext))]
    partial class AppDataContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.0");

            modelBuilder.Entity("ProjetoDietas.Models.Alimento", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasAnnotation("Relational:JsonPropertyName", "id");

                    b.Property<double>("Carboidratos")
                        .HasColumnType("REAL")
                        .HasAnnotation("Relational:JsonPropertyName", "carbohydrate_g");

                    b.Property<string>("Categoria")
                        .HasColumnType("TEXT")
                        .HasAnnotation("Relational:JsonPropertyName", "category");

                    b.Property<double>("EnergiaKcal")
                        .HasColumnType("REAL")
                        .HasAnnotation("Relational:JsonPropertyName", "energy_kcal");

                    b.Property<double>("FibraAlimentar")
                        .HasColumnType("REAL")
                        .HasAnnotation("Relational:JsonPropertyName", "fiber_g");

                    b.Property<double>("Lipideos")
                        .HasColumnType("REAL")
                        .HasAnnotation("Relational:JsonPropertyName", "lipid_g");

                    b.Property<string>("Nome")
                        .HasColumnType("TEXT")
                        .HasAnnotation("Relational:JsonPropertyName", "description");

                    b.Property<double>("Proteina")
                        .HasColumnType("REAL")
                        .HasAnnotation("Relational:JsonPropertyName", "protein_g");

                    b.Property<double>("Sodio")
                        .HasColumnType("REAL")
                        .HasAnnotation("Relational:JsonPropertyName", "sodium_mg");

                    b.HasKey("Id");

                    b.ToTable("Alimentos");
                });
#pragma warning restore 612, 618
        }
    }
}
